import type { Metadata } from "next";

import "./globals.css";
import Header from "./components/navbar/Header";
import Footer from "./components/Footer";


export const metadata: Metadata = {
  title: "Hey there",
  description: "Generated by @kostas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="https://upload.wikimedia.org/wikipedia/commons/thumb/7/75/Disc_Plain_yellow_dark.svg/2153px-Disc_Plain_yellow_dark.svg.png" />
      <body>
        <div>
          <Header/>
        </div>
        {children}
        <div className="w-full max-w-[1124px] mx-auto">
          <Footer/>
        </div>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></script>

      </body>
    </html>
  );
}
